### ISSUE TITLE
Adjust check usage script for Lawrencium

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/slurm-banking-utilities#4]
Make the check usage script compatible with the forthcoming deployment of MyLRC. Changes include:
- [x] Vary the `BASE_URL`:
    - The staging URL for LRC is https://scgup-dev.lbl.gov:8443.
    - The production URL for LRC will eventually be https://mylrc.lbl.gov.
    - The staging URL for BRC has been changed to: https://scgup-dev.lbl.gov.
- [x] Vary any error text to be appropriate for Lawrencium.

**Comment by ViRu-ThE-ViRuS** [comment]
pushed to master!
