### ISSUE TITLE
Adjust job completion log script for Lawrencium

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/slurm-banking-utilities#5]
Make the script for logging job completions compatible with the forthcoming deployment of MyLRC. Changes include:
- [ ] Vary the `BASE_URL`.
    - [ ] The path to the API is `/api`, not `/mybrc-rest`.

**Comment by ViRu-ThE-ViRuS** [comment]
added -T flag for target, choices are `mybrc` or `mylrc`.
